# Registers the service with https://snyk.roadie.so/catalog
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-AppRisk
  description: this is for testing backstage catalog yaml
  annotations:
    backstage.io/techdocs-ref: dir:.
    circleci.com/project-slug: github/snyk/issue-policies
    github.com/project-slug: snyk/issue-policies
    github.com/team-slug: snyk/narwhal
    snyk.io/accepts-user-input: yes
    snyk.io/jira-prefix: NARW
    snyk.io/criticality: "1"
  labels:
    snyk.io/businessCriticality: high
    snyk.io/visibility: public
    snyk.io/metadata-version: "2021-14-10"
  links:
    - title: Team Asks Channel
      url: https://snyk.slack.com/archives/CL5UPLZ3N
    - title: Vulnerabilities
      url: https://app.snyk.io/org/narwhal-xpq
    - title: Ignores SLO Dashboard
      url: https://app.datadoghq.com/slo/manage?query=api%3Aignores%20AND%20team%3Anarwhal%20AND%20service%3Aissue-policies
    - title: Issues SLO Dashboard
      url: https://app.datadoghq.com/slo/manage?query=api:issues%20AND%20team:narwhal%20AND%20service:issue-policies
  tags:
    - polaris-application
    - go
spec:
  type: snyk-deployed-fedramp
  lifecycle: "-"
  owner: narwhal
  system: platform-core
  providesApis:
    - Issues-Service_2022-05-11_experimental
    - Issues-Service_2022-10-28_experimental
    - Issues-Service_2022-11-09_experimental
    - Issues-Service_2023-01-13_experimental
    - Issues-Service_2023-02-17_experimental
    - Issues-Service_2023-03-10_experimental
    - Issues-Service_2023-06-22_experimental
    - Issues-Service_2023-08-28_experimental
    - Issues-Service_2023-09-29_beta
    - Issues-Service_2023-09-29_experimental
    - Issues-Service_2023-11-01_experimental
    - Issues-Service_2023-12-20_beta
    - Issues-Service_2023-12-20_experimental
    - Issues-Service_2024-01-23_beta
    - Issues-Service_2024-01-23_experimental
    - Issues-Service_2024-01-23_ga
---
# Generated by vervet, DO NOT EDIT
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test 1
  title: Snyk-goof testing
  annotations:
    api.snyk.io/generated-by: vervet
  labels:
    api.snyk.io/version-date: "2022-05-11"
    api.snyk.io/version-lifecycle: sunset
    api.snyk.io/version-stability: experimental
  tags:
    - 2022-05
    - experimental
    - sunset
spec:
  type: openapi
  lifecycle: sunset
  owner: narwhal
  definition:
    $text: internal/web/internal/api/rest/versions/2022-05-11~experimental/spec.json
---
# Generated by vervet, DO NOT EDIT
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test 1
  title: Snyk-goof testing
  annotations:
    api.snyk.io/generated-by: vervet
  labels:
    api.snyk.io/version-date: "2022-10-28"
    api.snyk.io/version-lifecycle: sunset
    api.snyk.io/version-stability: experimental
  tags:
    - 2022-10
    - experimental
    - sunset
spec:
  type: openapi
  lifecycle: sunset
  owner: narwhal
  definition:
    $text: internal/web/internal/api/rest/versions/2022-10-28~experimental/spec.json
---
# Generated by vervet, DO NOT EDIT
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test 1
  title: Snyk-goof testing
  annotations:
    api.snyk.io/generated-by: vervet
  labels:
    api.snyk.io/version-date: "2022-11-09"
    api.snyk.io/version-lifecycle: sunset
    api.snyk.io/version-stability: experimental
  tags:
    - 2022-11
    - experimental
    - sunset
spec:
  type: openapi
  lifecycle: sunset
  owner: narwhal
  definition:
    $text: internal/web/internal/api/private/versions/2022-11-09~experimental/spec.json
---
# Generated by vervet, DO NOT EDIT
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test 1
  title: Snyk-goof testing
  annotations:
    api.snyk.io/generated-by: vervet
  labels:
    api.snyk.io/version-date: "2023-01-13"
    api.snyk.io/version-lifecycle: sunset
    api.snyk.io/version-stability: experimental
  tags:
    - 2023-01
    - experimental
    - sunset
spec:
  type: openapi
  lifecycle: sunset
  owner: narwhal
  definition:
    $text: internal/web/internal/api/hidden/versions/2023-01-13~experimental/spec.json
---
# Generated by vervet, DO NOT EDIT
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test 1
  title: Snyk-goof testing
  annotations:
    api.snyk.io/generated-by: vervet
  labels:
    api.snyk.io/version-date: "2023-02-17"
    api.snyk.io/version-lifecycle: sunset
    api.snyk.io/version-stability: experimental
  tags:
    - 2023-02
    - experimental
    - sunset
spec:
  type: openapi
  lifecycle: sunset
  owner: narwhal
  definition:
    $text: internal/web/internal/api/hidden/versions/2023-02-17~experimental/spec.json
---
# Generated by vervet, DO NOT EDIT
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Issues-Service_2023-03-10_experimental
  title: Issues Service 2023-03-10 experimental
  annotations:
    api.snyk.io/generated-by: vervet
  labels:
    api.snyk.io/version-date: "2023-03-10"
    api.snyk.io/version-lifecycle: sunset
    api.snyk.io/version-stability: experimental
  tags:
    - 2023-03
    - experimental
    - sunset
spec:
  type: openapi
  lifecycle: sunset
  owner: narwhal
  definition:
    $text: internal/web/internal/api/rest/versions/2023-03-10~experimental/spec.json
---
# Generated by vervet, DO NOT EDIT
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Issues-Service_2023-06-22_experimental
  title: Issues Service 2023-06-22 experimental
  annotations:
    api.snyk.io/generated-by: vervet
  labels:
    api.snyk.io/version-date: "2023-06-22"
    api.snyk.io/version-lifecycle: sunset
    api.snyk.io/version-stability: experimental
  tags:
    - 2023-06
    - experimental
    - sunset
spec:
  type: openapi
  lifecycle: sunset
  owner: narwhal
  definition:
    $text: internal/web/internal/api/rest/versions/2023-06-22~experimental/spec.json
---
# Generated by vervet, DO NOT EDIT
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Issues-Service_2023-08-28_experimental
  title: Issues Service 2023-08-28 experimental
  annotations:
    api.snyk.io/generated-by: vervet
  labels:
    api.snyk.io/version-date: "2023-08-28"
    api.snyk.io/version-lifecycle: sunset
    api.snyk.io/version-stability: experimental
  tags:
    - 2023-08
    - experimental
    - sunset
spec:
  type: openapi
  lifecycle: sunset
  owner: narwhal
  definition:
    $text: internal/web/internal/api/private/versions/2023-08-28~experimental/spec.json
---
# Generated by vervet, DO NOT EDIT
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Issues-Service_2023-09-29_beta
  title: Issues Service 2023-09-29 beta
  annotations:
    api.snyk.io/generated-by: vervet
  labels:
    api.snyk.io/version-date: "2023-09-29"
    api.snyk.io/version-lifecycle: released
    api.snyk.io/version-stability: beta
  tags:
    - 2023-09
    - beta
    - released
spec:
  type: openapi
  lifecycle: beta
  owner: narwhal
  definition:
    $text: internal/web/internal/api/rest/versions/2023-09-29~beta/spec.json
---
# Generated by vervet, DO NOT EDIT
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Issues-Service_2023-09-29_experimental
  title: Issues Service 2023-09-29 experimental
  annotations:
    api.snyk.io/generated-by: vervet
  labels:
    api.snyk.io/version-date: "2023-09-29"
    api.snyk.io/version-lifecycle: sunset
    api.snyk.io/version-stability: experimental
  tags:
    - 2023-09
    - experimental
    - sunset
spec:
  type: openapi
  lifecycle: sunset
  owner: narwhal
  definition:
    $text: internal/web/internal/api/rest/versions/2023-09-29~experimental/spec.json
---
# Generated by vervet, DO NOT EDIT
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Issues-Service_2023-11-01_experimental
  title: Issues Service 2023-11-01 experimental
  annotations:
    api.snyk.io/generated-by: vervet
  labels:
    api.snyk.io/version-date: "2023-11-01"
    api.snyk.io/version-lifecycle: sunset
    api.snyk.io/version-stability: experimental
  tags:
    - 2023-11
    - experimental
    - sunset
spec:
  type: openapi
  lifecycle: sunset
  owner: narwhal
  definition:
    $text: internal/web/internal/api/hidden/versions/2023-11-01~experimental/spec.json
---
# Generated by vervet, DO NOT EDIT
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Issues-Service_2023-12-20_beta
  title: Issues Service 2023-12-20 beta
  annotations:
    api.snyk.io/generated-by: vervet
  labels:
    api.snyk.io/version-date: "2023-12-20"
    api.snyk.io/version-lifecycle: released
    api.snyk.io/version-stability: beta
  tags:
    - 2023-12
    - beta
    - released
spec:
  type: openapi
  lifecycle: beta
  owner: narwhal
  definition:
    $text: internal/web/internal/api/rest/versions/2023-12-20~beta/spec.json
---
# Generated by vervet, DO NOT EDIT
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Issues-Service_2023-12-20_experimental
  title: Issues Service 2023-12-20 experimental
  annotations:
    api.snyk.io/generated-by: vervet
  labels:
    api.snyk.io/version-date: "2023-12-20"
    api.snyk.io/version-lifecycle: sunset
    api.snyk.io/version-stability: experimental
  tags:
    - 2023-12
    - experimental
    - sunset
spec:
  type: openapi
  lifecycle: sunset
  owner: narwhal
  definition:
    $text: internal/web/internal/api/rest/versions/2023-12-20~experimental/spec.json
---
# Generated by vervet, DO NOT EDIT
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Issues-Service_2024-01-23_beta
  title: Issues Service 2024-01-23 beta
  annotations:
    api.snyk.io/generated-by: vervet
  labels:
    api.snyk.io/version-date: "2024-01-23"
    api.snyk.io/version-lifecycle: released
    api.snyk.io/version-stability: beta
  tags:
    - 2024-01
    - beta
    - released
spec:
  type: openapi
  lifecycle: beta
  owner: narwhal
  definition:
    $text: internal/web/internal/api/rest/versions/2024-01-23~beta/spec.json
---
# Generated by vervet, DO NOT EDIT
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Issues-Service_2024-01-23_experimental
  title: Issues Service 2024-01-23 experimental
  annotations:
    api.snyk.io/generated-by: vervet
  labels:
    api.snyk.io/version-date: "2024-01-23"
    api.snyk.io/version-lifecycle: deprecated
    api.snyk.io/version-stability: experimental
  tags:
    - 2024-01
    - experimental
    - deprecated
spec:
  type: openapi
  lifecycle: deprecated
  owner: narwhal
  definition:
    $text: internal/web/internal/api/rest/versions/2024-01-23~experimental/spec.json
---
# Generated by vervet, DO NOT EDIT
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Issues-Service_2024-01-23_ga
  title: Issues Service 2024-01-23 ga
  annotations:
    api.snyk.io/generated-by: vervet
  labels:
    api.snyk.io/version-date: "2024-01-23"
    api.snyk.io/version-lifecycle: released
    api.snyk.io/version-stability: ga
  tags:
    - 2024-01
    - ga
    - released
spec:
  type: openapi
  lifecycle: ga
  owner: narwhal
  definition:
    $text: internal/web/internal/api/rest/versions/2024-01-23/spec.json
